[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
presale = "J1g88rh5zyqG17AXAd66MUXTfRMa2sksR1wSDP6Ly3NC"

[programs.localnet]
presale = "J1g88rh5zyqG17AXAd66MUXTfRMa2sksR1wSDP6Ly3NC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "`./pk/user.json`"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
